name: airy_multi_pull
description: "This is the successor project to multi_pull"
version: 0.0.2
homepage: https://x.com/airy_jingo
### https://www.airy-note.com/

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
